[general]
destination = "$HOME/.config/hypr/monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_AC"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_AC"


[profiles.lg34]
config_file = "$HOME/.config/hyprdynamicmonitors/hyprconfigs/lg34.go.tmpl"
config_file_type = "template"
[profiles.lg34.conditions]

[[profiles.lg34.conditions.required_monitors]]
description = "Lenovo Group Limited N160JCA-GT1"
monitor_tag = "monitor0"

[[profiles.lg34.conditions.required_monitors]]
description = "LG Electronics LG ULTRAGEAR 306NTDV4P106"
monitor_tag = "monitor1"


[profiles.default]
config_file = "$HOME/.config/hyprdynamicmonitors/hyprconfigs/default.go.tmpl"
config_file_type = "template"
[profiles.default.conditions]

[[profiles.default.conditions.required_monitors]]
description = "Lenovo Group Limited N160JCA-GT1"
monitor_tag = "monitor0"
