[ids]
*
# exclude Kinesis Adv360
-29ea:0360
# exclude Glove80
-16c0:27db

[main]
capslock = esc

# --- LEFT OF SPACE ---
# target sequence: Super, Alt, Ctrl (thumb)
leftcontrol = leftmeta
leftmeta = leftalt
leftalt = leftcontrol

# --- RIGHT OF SPACE ---
# target sequence: Ctrl, Alt (thumb)
rightalt = rightcontrol
# consistent Alt with variable layouts
rightcontrol = rightalt
rightmeta = rightalt
# Copilot
leftshift+leftmeta+f23 = rightalt
compose = rightalt
menu = rightalt
